In [1]:
import numpy as np

### 1. Что будет выведено на экран? a = np.arange(4).reshape(2,2) a += 0.5 print(a). Почему так?   
0.5 1.5   
2.5 3.5


In [59]:
a = np.arange(4).reshape(2,2)
a += 0.5
print(a)

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

a += b  equal to np.add(a, b, cast ='same_kind')

In [5]:
a = np.arange(4).reshape(2,2) 
a = a + 0.5
print(a)

[[0.5 1.5]
 [2.5 3.5]]


In [52]:
a = np.arange(4).reshape(2,2).astype('float')
a += 0.5
print(a)

[[0.5 1.5]
 [2.5 3.5]]


In [49]:
a = np.arange(4).reshape(2,2)
b = 0.5
cast_types = ['no','equiv','safe', 'same_kind','unsafe']
for cast in cast_types:
    print(cast, np.can_cast(b, 'int32', casting=cast))

no False
equiv False
safe False
same_kind False
unsafe True


### 2. Создайте масив из четырех элементов: 0, 10, 20, 30 2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго, больше предыдущего элемента этой же строки на 1.

In [54]:
a = np.array((0, 10, 20, 30))

In [76]:
res = [a + i for i in range(5)] # from list
np.array(res).T

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [82]:
(a + np.arange(5).reshape(-1,1)).T # with broadcasting

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

### 3. Какой shape будет у результата операции np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)?

(0, 1, 2, 3, 4) + (0, 1, 2, 3, 4).T

0 1 2 3 4   0 0 0 0 0    
0 1 2 3 4   1 1 1 1 1
0 1 2 3 4   2 2 2 2 2
0 1 2 3 4   3 3 3 3 3
0 1 2 3 4   4 4 4 4 4

In [77]:
np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### 4. Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке. done

In [213]:
%%timeit
a = np.zeros((8,8))
a[::2, 1::2] = 1
a[1::2, ::2] = 1

2.24 µs ± 13 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [214]:
7 % 2

1

In [215]:
%%timeit
a = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2:
            a[i,j] = 1

15 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 5. 1. Создайте одномерный массив целых чисел от 1 до 5 2. Вставьте 0 между каждой парой соседних элементов. done

In [156]:
a = np.arange(1, 6)
b = np.zeros(9)
b[::2] = a
print(b)

[1. 0. 2. 0. 3. 0. 4. 0. 5.]


In [157]:
np.insert(a , [1, 2, 3, 4], 0) # without creating additional array

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

### 6. 1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9 2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [143]:
a = np.random.uniform(0, 9, (3,3))
print(a)

[[0.62219562 5.11646737 2.84646967]
 [2.58353374 0.7632711  5.71742966]
 [4.46638099 4.46386482 4.08895696]]


In [146]:
row_ind = np.argsort(a[:,1])
print(a[[row_ind]])

[[2.58353374 0.7632711  5.71742966]
 [4.46638099 4.46386482 4.08895696]
 [0.62219562 5.11646737 2.84646967]]


### 7. Поменяйте местами первую и вторую строки двумерного массива

In [194]:
a = np.random.randint(0, 10, (5,5))
print(a)

[[0 6 8 0 4]
 [0 5 6 3 2]
 [3 2 5 2 5]
 [8 4 2 7 7]
 [0 9 0 8 4]]


In [195]:
a[[1, 0]] = a[[0, 1]]
print(a)

[[0 5 6 3 2]
 [0 6 8 0 4]
 [3 2 5 2 5]
 [8 4 2 7 7]
 [0 9 0 8 4]]


### 8. 1. Создайте массив, заполненный случайными значениями 2. Замените максимальные значения массива средним

In [65]:
a = np.random.randint(1, 10, 10).astype('float')
print(a)
print(a.mean(), a.max())

[8. 8. 5. 5. 3. 6. 6. 7. 6. 3.]
5.7 8.0


In [66]:
mask = np.where(a==a.max())
a[mask] = a.mean()
print(a)

[5.7 5.7 5.  5.  3.  6.  6.  7.  6.  3. ]


### 9.  scale to [0,1]. done

In [149]:
arr = np.random.randint(1, 10, 10)
print(arr)

[9 6 3 6 4 4 3 9 3 5]


In [150]:
a, b = arr.min(), arr.max()

In [151]:
k, c = 1 / (b - a), 1 - b / (b - a) # ugly and resulted in list instead of np.array

In [152]:
new_arr = [k * i + c for i in arr]
print(new_arr)

[1.0, 0.5, 0.0, 0.5, 0.16666666666666663, 0.16666666666666663, 0.0, 1.0, 0.0, 0.33333333333333326]


In [154]:
arr = (arr - arr.min()) / (arr.max() - arr.min()) # ok
print(arr)

[1.         0.5        0.         0.5        0.16666667 0.16666667
 0.         1.         0.         0.33333333]


### 10. not finished

In [159]:
a = np.array([[np.nan, 2, 3], [4, np.nan, 6], [7, 8, np.nan]])
print(a)

[[nan  2.  3.]
 [ 4. nan  6.]
 [ 7.  8. nan]]


In [168]:
ind = np.argwhere(np.isnan(a))

### 11. done

In [68]:
a = np.array(([0, 1, 2], [0, 3, 4], [0, 5, 6]))
print(a)

[[0 1 2]
 [0 3 4]
 [0 5 6]]


In [45]:
def zeros_col(a): # 1 approach
    for col in a.T:
        if sum(col) == 0:
            return True
    return False

zeros_col(a)

In [205]:
a = np.random.randint(0, 2, (3,3))
print(a)

[[0 0 1]
 [0 0 1]
 [0 0 0]]


In [207]:
0 in np.sum(a, axis=0) # 2 approach

True

### 12. Путь даны два массива одинакового размера. Поэлементно разделите один массив на другой. В случае, если делитель равен нулю, соответствующему элементу результирующего массива присвойте нуль

In [73]:
size = 5
a, b = np.random.randint(0 , 5 , (2,size))
print(a, b)

[2 3 1 3 1] [0 0 2 1 4]


In [74]:
c = np.divide(a, b)
c[np.isinf(c)] = 0
print(c)

[0.   0.   0.5  3.   0.25]


C:\Users\Nikita\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


### 13. Пусть заданы два массива x an i. Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массиве i.

In [2]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 8])

In [3]:
%%timeit
for ind in i:
    x[ind] += 1

5.83 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
%%timeit
np.add.at(x, i, 1)

5.83 µs ± 180 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
%%timeit
np.bincount(i, minlength=len(x))

1.5 µs ± 23.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### 14. По двум входным одномерным массивам одинаковой длины составьте массив пар элементов с одинаковыми индексами. Решите задачу на примере массивов x and y. done

In [87]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6 ,7 ,8])
def f(x, y):
    return list(zip(x,y))
print(f(x, y))

[(1, 5), (2, 6), (3, 7), (4, 8)]


In [93]:
np.array([x,y]).T[1] # numpy approach

array([2, 6])

### 15. Для заданного двумерного массива потсройте трехмерный массив, содержащий всевозможные неперекрывающиеся блоки размера 3х3, начиная с левого верхнего угла. Если высота / ширина исходного массива не кратна трем, исключите из рассмотрения последние строки/столбцы. Решите задачу на примере массива x 

In [3]:
a = np.arange(49).reshape(7,7)
print(a)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


In [4]:
sub_shape = (3,3)
view_shape = tuple(np.subtract(a.shape, sub_shape) + 1) + sub_shape
strides = a.strides + a.strides

sub_matrices = np.lib.stride_tricks.as_strided(a,view_shape,strides)

In [10]:
np.subtract()

(5, 5, 3, 3)

In [9]:
a.strides

(28, 4)

In [8]:
def f(x): # ugly
    num_windx = x.shape[0] // 3
    num_windy = x.shape[1] // 3
    res = []
    for i in range(num_windx):
        for j in range(num_windy):
            res.append(x[3*i:3*(i + 1), 3*j:3*(j + 1)])
    return res

In [58]:
res = f(x)
print(res)

[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]]
[[ 3  4  5]
 [10 11 12]
 [17 18 19]]
[[21 22 23]
 [28 29 30]
 [35 36 37]]
[[24 25 26]
 [31 32 33]
 [38 39 40]]
None
