In [1]:
import numpy as np

### 1. Что будет выведено на экран? a = np.arange(4).reshape(2,2) a += 0.5 print(a). Почему так?   
0.5 1.5   
2.5 3.5


In [9]:
a = np.arange(4).reshape(2,2)
a += 0.5
print(a)

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

a += b  equal to np.add(a, b, cast ='same_kind')

In [5]:
a = np.arange(4).reshape(2,2) 
a = a + 0.5
print(a)

[[0.5 1.5]
 [2.5 3.5]]


In [52]:
a = np.arange(4).reshape(2,2).astype('float')
a += 0.5
print(a)

[[0.5 1.5]
 [2.5 3.5]]


In [49]:
a = np.arange(4).reshape(2,2)
b = 0.5
cast_types = ['no','equiv','safe', 'same_kind','unsafe']
for cast in cast_types:
    print(cast, np.can_cast(b, 'int32', casting=cast))

no False
equiv False
safe False
same_kind False
unsafe True


### 2. Создайте масив из четырех элементов: 0, 10, 20, 30 2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго, больше предыдущего элемента этой же строки на 1.

In [54]:
a = np.array((0, 10, 20, 30))

In [76]:
res = [a + i for i in range(5)] # from list
np.array(res).T

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [82]:
(a + np.arange(5).reshape(-1,1)).T # with broadcasting

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

### 3. Какой shape будет у результата операции np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)?

(0, 1, 2, 3, 4) + (0, 1, 2, 3, 4).T

0 1 2 3 4   0 0 0 0 0    
0 1 2 3 4   1 1 1 1 1
0 1 2 3 4   2 2 2 2 2
0 1 2 3 4   3 3 3 3 3
0 1 2 3 4   4 4 4 4 4

In [77]:
np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### 4. Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

In [94]:
a = np.zeros((8,8))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 5. 1. Создайте одномерный массив целых чисел от 1 до 5 2. Вставьте 0 между каждой парой соседних элементов

In [114]:
a = np.arange(1, 6)
b = np.zeros(10)
b[::2] = a
print(b)

[1. 0. 2. 0. 3. 0. 4. 0. 5. 0.]


### 6. 1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9 2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [143]:
a = np.random.uniform(0, 9, (3,3))
print(a)

[[0.62219562 5.11646737 2.84646967]
 [2.58353374 0.7632711  5.71742966]
 [4.46638099 4.46386482 4.08895696]]


In [146]:
row_ind = np.argsort(a[:,1])
print(a[[row_ind]])

[[2.58353374 0.7632711  5.71742966]
 [4.46638099 4.46386482 4.08895696]
 [0.62219562 5.11646737 2.84646967]]


### 7. Поменяйте местами первую и вторую строки двумерного массива

In [194]:
a = np.random.randint(0, 10, (5,5))
print(a)

[[0 6 8 0 4]
 [0 5 6 3 2]
 [3 2 5 2 5]
 [8 4 2 7 7]
 [0 9 0 8 4]]


In [195]:
a[[1, 0]] = a[[0, 1]]
print(a)

[[0 5 6 3 2]
 [0 6 8 0 4]
 [3 2 5 2 5]
 [8 4 2 7 7]
 [0 9 0 8 4]]


### 8. 1. Создайте массив, заполненный случайными значениями 2. Замените максимальные значения массива средним

In [226]:
a = np.random.randint(1, 10, 10).astype('float')
print(a)
print(a.mean(), a.max())

[8. 9. 5. 1. 5. 9. 6. 6. 8. 8.]
6.5 9.0


In [227]:
mask = np.where(a==a.max())
a[mask] = a.mean()
print(a)

[8.  6.5 5.  1.  5.  6.5 6.  6.  8.  8. ]
